Namespace Ladisac.Planillas.Constants
    Public Class BuscadoresNames
        Public Shared ReadOnly Conceptos As String = "ConceptosBuscar"
        Public Shared ReadOnly TiposContratos As String = "TiposContratos"
        Public Shared ReadOnly Periodisidad As String = "Periodisidad"
        Public Shared ReadOnly TiposCargos As String = "TiposCargos"
        Public Shared ReadOnly NIvelEducacion As String = "NivelEducacion"
        Public Shared ReadOnly ConvenioDobleTributacion As String = "ConvenioDobleTributacionRepositorio"
        Public Shared ReadOnly TiposTrabajador As String = "TiposTrabajador"
        Public Shared ReadOnly RegimenLaboral As String = "RegimenLaboral"
        Public Shared ReadOnly RegimenPensionario As String = "RegimenPensionario"
        Public Shared ReadOnly SituacionEspecialTrabajador As String = "SituacionEspecialTrabajador"
        Public Shared ReadOnly SituacionTrabajador As String = "SituacionTrabajador"
        Public Shared ReadOnly TiposPlanillas As String = "TiposPlanillas"
        Public Shared ReadOnly ConceptosPlanilla As String = "ConceptosPlanilla"
        Public Shared ReadOnly DatosLaborales As String = "DatosLaborales"
        Public Shared ReadOnly BuscarPersona As String = "BuscarPersona"
        Public Shared ReadOnly Bancos As String = "Bancos"
        Public Shared ReadOnly AreaTrabajos As String = "AreaTrabajos"
        Public Shared ReadOnly DetalleConceptoPensionario As String = "DetalleConceptoPensionario"
        Public Shared ReadOnly ConceptosTrabajador As String = "ConceptosTrabajador"
        Public Shared ReadOnly TiposTareaTrabajo As String = "TiposTareaTrabajo"
        Public Shared ReadOnly DatosTrabajadorJudicial As String = "DatosTrabajadorJudicial"
        Public Shared ReadOnly DetalleConceptosPlanillasLista As String = "DetalleConceptosPlanillas"
        Public Shared ReadOnly PrestamosTrabajador As String = "PrestamosTrabajador"
        Public Shared ReadOnly TareaTrabajo As String = "TareaTrabajo"
        Public Shared ReadOnly ArticulosLista As String = "ArticulosLista"

        Public Shared ReadOnly GrupoTrabajoHoras As String = "GrupoTrabajoHoras"
        Public Shared ReadOnly GrupoTrabajoTareo As String = "GrupoTrabajoTareo"
        Public Shared ReadOnly GrupoTrabajoTarea As String = "GrupoTrabajoTarea"
        Public Shared ReadOnly GrupoTrabajoProduccion As String = "GrupoTrabajoProduccion"
        Public Shared ReadOnly GrupoTrabajoSinFechaProduccion As String = "GrupoTrabajoSinFechaProduccion"
        Public Shared ReadOnly GrupoTrabajoConteoCargaProduccion As String = "GrupoTrabajoConteoCargaProduccion"
        Public Shared ReadOnly GrupoTrabajoQuemaSecadeo As String = "GrupoTrabajoQuemaSecadeo"

        Public Shared ReadOnly PermisosTrabajador As String = "Permisos Trabajador"
        Public Shared ReadOnly TrabajadorHoras As String = "Trabajador Horas"
        Public Shared ReadOnly CalendarioDias As String = "CalendarioDias"
        Public Shared ReadOnly ReparoTrabajador As String = "ReparoTrabajador"
        Public Shared ReadOnly Comedor As String = "Importar Conceptos"
        Public Shared ReadOnly CentroRiesgo As String = "CentroRiesgo"
        Public Shared ReadOnly BuscarPlanilla As String = "BuscarPlanilla"
        Public Shared ReadOnly PlanillaMantenimiento As String = "Planilla Mantenimiento"
        Public Shared ReadOnly ReporteDatosTrabajadorJudicial As String = "Reporte Datos Trabajador Judicial"
        Public Shared ReadOnly ReportePersonaTipoFichas As String = "Fichas Personal del Trabajador"
        Public Shared ReadOnly ExportarPlameTRegistor As String = "Exportar Plame y T-Registor"
        Public Shared ReadOnly GrupoMantenimiento As String = "Grupo Mantenimiento"
        Public Shared ReadOnly OrdenTrabajo As String = "Orden de Trabajo"
        Public Shared ReadOnly Marcacion As String = "Marcacion Asistencia "
        Public Shared ReadOnly CronogramaVacaciones As String = "ConogramaVacaciones"
        Public Shared ReadOnly GrupoTrabajoDiasDescanso As String = "Grupo Trabajo Dias Descanso"
        Public Shared ReadOnly GrupoEmpleado As String = "Grupo Empleado"
        '-----reportes 
        Public Shared ReadOnly ReportePeriodoLaboral As String = "Reporte Periodo Laboral"
        Public Shared ReadOnly ReportePeriodoVacaciones As String = "Reporte Periodo Vacaciones"
        Public Shared ReadOnly ReporteComedor As String = "Reporte Conceptos Importados"

    End Class
End Namespace
