'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
'     el código se vuelve a generar.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices

<DataContract(IsReference:=True)>
<KnownType(GetType(Moneda))>
<KnownType(GetType(Usuarios))>
<KnownType(GetType(TipoPersonas))>
Partial Public Class Comision
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Propiedades primitivas"


	<DataContract()> Partial Public Structure PropertyNames
				public shared COM_ID As string = "COM_ID"
				public shared COM_DESCRIPCION As string = "COM_DESCRIPCION"
				public shared MON_ID As string = "MON_ID"
				public shared COM_POR_CUO_MEN As string = "COM_POR_CUO_MEN"
				public shared COM_CONTRAVALOR As string = "COM_CONTRAVALOR"
				public shared COM_POR_OBJ_MEN As string = "COM_POR_OBJ_MEN"
				public shared COM_VENTA_CAN As string = "COM_VENTA_CAN"
				public shared COM_FORMULA As string = "COM_FORMULA"
				public shared USU_ID As string = "USU_ID"
				public shared COM_FEC_GRAB As string = "COM_FEC_GRAB"
				public shared COM_ESTADO As string = "COM_ESTADO"
		    End Structure
	



    <DataMember()>
    Public Property COM_ID() As String
        Get
            Return _cOM_ID
        End Get
        Set(ByVal value As String)
            If Not Equals(_cOM_ID, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("La propiedad 'COM_ID' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.")
                End If
                _cOM_ID = value
                OnPropertyChanged("COM_ID")
            End If
        End Set
    End Property

    Private _cOM_ID As String

    <DataMember()>
    Public Property COM_DESCRIPCION() As String
        Get
            Return _cOM_DESCRIPCION
        End Get
        Set(ByVal value As String)
            If Not Equals(_cOM_DESCRIPCION, value) Then
                _cOM_DESCRIPCION = value
                OnPropertyChanged("COM_DESCRIPCION")
            End If
        End Set
    End Property

    Private _cOM_DESCRIPCION As String

    <DataMember()>
    Public Property MON_ID() As String
        Get
            Return _mON_ID
        End Get
        Set(ByVal value As String)
            If Not Equals(_mON_ID, value) Then
                ChangeTracker.RecordOriginalValue("MON_ID", _mON_ID)
                If Not IsDeserializing Then
                    If Moneda IsNot Nothing AndAlso Not Equals(Moneda.MON_ID, value) Then
                        Moneda = Nothing
                    End If
                End If
                _mON_ID = value
                OnPropertyChanged("MON_ID")
            End If
        End Set
    End Property

    Private _mON_ID As String

    <DataMember()>
    Public Property COM_POR_CUO_MEN() As Decimal
        Get
            Return _cOM_POR_CUO_MEN
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_cOM_POR_CUO_MEN, value) Then
                _cOM_POR_CUO_MEN = value
                OnPropertyChanged("COM_POR_CUO_MEN")
            End If
        End Set
    End Property

    Private _cOM_POR_CUO_MEN As Decimal

    <DataMember()>
    Public Property COM_CONTRAVALOR() As Decimal
        Get
            Return _cOM_CONTRAVALOR
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_cOM_CONTRAVALOR, value) Then
                _cOM_CONTRAVALOR = value
                OnPropertyChanged("COM_CONTRAVALOR")
            End If
        End Set
    End Property

    Private _cOM_CONTRAVALOR As Decimal

    <DataMember()>
    Public Property COM_POR_OBJ_MEN() As Decimal
        Get
            Return _cOM_POR_OBJ_MEN
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_cOM_POR_OBJ_MEN, value) Then
                _cOM_POR_OBJ_MEN = value
                OnPropertyChanged("COM_POR_OBJ_MEN")
            End If
        End Set
    End Property

    Private _cOM_POR_OBJ_MEN As Decimal

    <DataMember()>
    Public Property COM_VENTA_CAN() As Short
        Get
            Return _cOM_VENTA_CAN
        End Get
        Set(ByVal value As Short)
            If Not Equals(_cOM_VENTA_CAN, value) Then
                _cOM_VENTA_CAN = value
                OnPropertyChanged("COM_VENTA_CAN")
            End If
        End Set
    End Property

    Private _cOM_VENTA_CAN As Short

    <DataMember()>
    Public Property COM_FORMULA() As String
        Get
            Return _cOM_FORMULA
        End Get
        Set(ByVal value As String)
            If Not Equals(_cOM_FORMULA, value) Then
                _cOM_FORMULA = value
                OnPropertyChanged("COM_FORMULA")
            End If
        End Set
    End Property

    Private _cOM_FORMULA As String

    <DataMember()>
    Public Property USU_ID() As String
        Get
            Return _uSU_ID
        End Get
        Set(ByVal value As String)
            If Not Equals(_uSU_ID, value) Then
                ChangeTracker.RecordOriginalValue("USU_ID", _uSU_ID)
                If Not IsDeserializing Then
                    If Usuarios IsNot Nothing AndAlso Not Equals(Usuarios.USU_ID, value) Then
                        Usuarios = Nothing
                    End If
                End If
                _uSU_ID = value
                OnPropertyChanged("USU_ID")
            End If
        End Set
    End Property

    Private _uSU_ID As String

    <DataMember()>
    Public Property COM_FEC_GRAB() As Date
        Get
            Return _cOM_FEC_GRAB
        End Get
        Set(ByVal value As Date)
            If Not Equals(_cOM_FEC_GRAB, value) Then
                _cOM_FEC_GRAB = value
                OnPropertyChanged("COM_FEC_GRAB")
            End If
        End Set
    End Property

    Private _cOM_FEC_GRAB As Date

    <DataMember()>
    Public Property COM_ESTADO() As Boolean
        Get
            Return _cOM_ESTADO
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_cOM_ESTADO, value) Then
                _cOM_ESTADO = value
                OnPropertyChanged("COM_ESTADO")
            End If
        End Set
    End Property

    Private _cOM_ESTADO As Boolean

#End Region
#Region "Propiedades de navegación"

    <DataMember()>
    Public Property Moneda() As Moneda
        Get
            Return _moneda
        End Get
        Set(ByVal value As Moneda)
            If _moneda IsNot value Then
                Dim previousValue As Moneda = _moneda
                _moneda = value
                FixupMoneda(previousValue)
                OnNavigationPropertyChanged("Moneda")
            End If
        End Set
    End Property

    Private _moneda As Moneda


    <DataMember()>
    Public Property Usuarios() As Usuarios
        Get
            Return _usuarios
        End Get
        Set(ByVal value As Usuarios)
            If _usuarios IsNot value Then
                Dim previousValue As Usuarios = _usuarios
                _usuarios = value
                FixupUsuarios(previousValue)
                OnNavigationPropertyChanged("Usuarios")
            End If
        End Set
    End Property

    Private _usuarios As Usuarios


    <DataMember()>
    Public Property TipoPersonas() As TrackableCollection(Of TipoPersonas)
        Get
            If _tipoPersonas Is Nothing Then
                _tipoPersonas = New TrackableCollection(Of TipoPersonas)
                AddHandler _tipoPersonas.CollectionChanged, AddressOf FixupTipoPersonas
            End If
            Return _tipoPersonas
        End Get
        Set(ByVal value As TrackableCollection(Of TipoPersonas))
            If Not Object.ReferenceEquals(_tipoPersonas, value) Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("No se puede establecer el elemento FixupChangeTrackingCollection cuando se ha habilitado ChangeTracking")
                End If
                If _tipoPersonas IsNot Nothing Then
                    RemoveHandler _tipoPersonas.CollectionChanged, AddressOf FixupTipoPersonas
                End If
                _tipoPersonas = value
                If _tipoPersonas IsNot Nothing Then
                    AddHandler _tipoPersonas.CollectionChanged, AddressOf FixupTipoPersonas
                End If
                OnNavigationPropertyChanged("TipoPersonas")
            End If
        End Set
    End Property

    Private _tipoPersonas As TrackableCollection(Of TipoPersonas)

#End Region
#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        Moneda = Nothing
        Usuarios = Nothing
        TipoPersonas.Clear()
    End Sub

#End Region
#Region "Corrección de asociación"

    Private Sub FixupMoneda(ByVal previousValue As Moneda)
        If IsDeserializing Then
            Return
        End If

        If Moneda IsNot Nothing Then
            MON_ID = Moneda.MON_ID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Moneda") AndAlso
                ChangeTracker.OriginalValues("Moneda") Is Moneda Then
                ChangeTracker.OriginalValues.Remove("Moneda")
            Else
                ChangeTracker.RecordOriginalValue("Moneda", previousValue)
            End If
            If Moneda IsNot Nothing AndAlso Not Moneda.ChangeTracker.ChangeTrackingEnabled Then
                Moneda.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupUsuarios(ByVal previousValue As Usuarios)
        If IsDeserializing Then
            Return
        End If

        If Usuarios IsNot Nothing Then
            USU_ID = Usuarios.USU_ID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Usuarios") AndAlso
                ChangeTracker.OriginalValues("Usuarios") Is Usuarios Then
                ChangeTracker.OriginalValues.Remove("Usuarios")
            Else
                ChangeTracker.RecordOriginalValue("Usuarios", previousValue)
            End If
            If Usuarios IsNot Nothing AndAlso Not Usuarios.ChangeTracker.ChangeTrackingEnabled Then
                Usuarios.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupTipoPersonas(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As TipoPersonas In e.NewItems
                item.Comision = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("TipoPersonas", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As TipoPersonas In e.OldItems
                If ReferenceEquals(item.Comision, Me) Then
                    item.Comision = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("TipoPersonas", item)
                End If
            Next
        End If
    End Sub

#End Region
End Class
