'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
'     el código se vuelve a generar.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices

<DataContract(IsReference:=True)>
<KnownType(GetType(Articulos))>
<KnownType(GetType(CtaCte))>
<KnownType(GetType(DetalleTipoDocumentos))>
<KnownType(GetType(TipoDocumentos))>
<KnownType(GetType(Usuarios))>
Partial Public Class DetalleAfectaProductoDocumentos
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Propiedades primitivas"


	<DataContract()> Partial Public Structure PropertyNames
				public shared TDO_ID As string = "TDO_ID"
				public shared DTD_ID As string = "DTD_ID"
				public shared DAP_SERIE As string = "DAP_SERIE"
				public shared DAP_NUMERO As string = "DAP_NUMERO"
				public shared DAP_ITEM As string = "DAP_ITEM"
				public shared TDO_ID_AFP As string = "TDO_ID_AFP"
				public shared DTD_ID_AFP As string = "DTD_ID_AFP"
				public shared CCT_ID_AFP As string = "CCT_ID_AFP"
				public shared DOC_SERIE_AFP As string = "DOC_SERIE_AFP"
				public shared DOC_NUMERO_AFP As string = "DOC_NUMERO_AFP"
				public shared ART_ID As string = "ART_ID"
				public shared DAP_CANTIDAD As string = "DAP_CANTIDAD"
				public shared DAP_OBS As string = "DAP_OBS"
				public shared USU_ID As string = "USU_ID"
				public shared DAP_FEC_GRAB As string = "DAP_FEC_GRAB"
				public shared DAP_ESTADO As string = "DAP_ESTADO"
				public shared TDO_ID_DEV As string = "TDO_ID_DEV"
				public shared DTD_ID_DEV As string = "DTD_ID_DEV"
				public shared CCT_ID_DEV As string = "CCT_ID_DEV"
				public shared DES_SERIE_DEV As string = "DES_SERIE_DEV"
				public shared DES_NUMERO_DEV As string = "DES_NUMERO_DEV"
				public shared ART_ID_DEV As string = "ART_ID_DEV"
				public shared DDE_CANTIDAD_DEV As string = "DDE_CANTIDAD_DEV"
		    End Structure
	



    <DataMember()>
    Public Property TDO_ID() As String
        Get
            Return _tDO_ID
        End Get
        Set(ByVal value As String)
            If Not Equals(_tDO_ID, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("La propiedad 'TDO_ID' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.")
                End If
                If Not IsDeserializing Then
                    If TipoDocumentos IsNot Nothing AndAlso Not Equals(TipoDocumentos.TDO_ID, value) Then
                        TipoDocumentos = Nothing
                    End If
                End If
                _tDO_ID = value
                OnPropertyChanged("TDO_ID")
            End If
        End Set
    End Property

    Private _tDO_ID As String

    <DataMember()>
    Public Property DTD_ID() As String
        Get
            Return _dTD_ID
        End Get
        Set(ByVal value As String)
            If Not Equals(_dTD_ID, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("La propiedad 'DTD_ID' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.")
                End If
                If Not IsDeserializing Then
                    If DetalleTipoDocumentos IsNot Nothing AndAlso Not Equals(DetalleTipoDocumentos.DTD_ID, value) Then
                        DetalleTipoDocumentos = Nothing
                    End If
                End If
                _dTD_ID = value
                OnPropertyChanged("DTD_ID")
            End If
        End Set
    End Property

    Private _dTD_ID As String

    <DataMember()>
    Public Property DAP_SERIE() As String
        Get
            Return _dAP_SERIE
        End Get
        Set(ByVal value As String)
            If Not Equals(_dAP_SERIE, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("La propiedad 'DAP_SERIE' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.")
                End If
                _dAP_SERIE = value
                OnPropertyChanged("DAP_SERIE")
            End If
        End Set
    End Property

    Private _dAP_SERIE As String

    <DataMember()>
    Public Property DAP_NUMERO() As String
        Get
            Return _dAP_NUMERO
        End Get
        Set(ByVal value As String)
            If Not Equals(_dAP_NUMERO, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("La propiedad 'DAP_NUMERO' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.")
                End If
                _dAP_NUMERO = value
                OnPropertyChanged("DAP_NUMERO")
            End If
        End Set
    End Property

    Private _dAP_NUMERO As String

    <DataMember()>
    Public Property DAP_ITEM() As Decimal
        Get
            Return _dAP_ITEM
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_dAP_ITEM, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("La propiedad 'DAP_ITEM' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.")
                End If
                _dAP_ITEM = value
                OnPropertyChanged("DAP_ITEM")
            End If
        End Set
    End Property

    Private _dAP_ITEM As Decimal

    <DataMember()>
    Public Property TDO_ID_AFP() As String
        Get
            Return _tDO_ID_AFP
        End Get
        Set(ByVal value As String)
            If Not Equals(_tDO_ID_AFP, value) Then
                ChangeTracker.RecordOriginalValue("TDO_ID_AFP", _tDO_ID_AFP)
                If Not IsDeserializing Then
                    If TipoDocumentos1 IsNot Nothing AndAlso Not Equals(TipoDocumentos1.TDO_ID, value) Then
                        TipoDocumentos1 = Nothing
                    End If
                End If
                _tDO_ID_AFP = value
                OnPropertyChanged("TDO_ID_AFP")
            End If
        End Set
    End Property

    Private _tDO_ID_AFP As String

    <DataMember()>
    Public Property DTD_ID_AFP() As String
        Get
            Return _dTD_ID_AFP
        End Get
        Set(ByVal value As String)
            If Not Equals(_dTD_ID_AFP, value) Then
                ChangeTracker.RecordOriginalValue("DTD_ID_AFP", _dTD_ID_AFP)
                If Not IsDeserializing Then
                    If DetalleTipoDocumentos1 IsNot Nothing AndAlso Not Equals(DetalleTipoDocumentos1.DTD_ID, value) Then
                        DetalleTipoDocumentos1 = Nothing
                    End If
                End If
                _dTD_ID_AFP = value
                OnPropertyChanged("DTD_ID_AFP")
            End If
        End Set
    End Property

    Private _dTD_ID_AFP As String

    <DataMember()>
    Public Property CCT_ID_AFP() As String
        Get
            Return _cCT_ID_AFP
        End Get
        Set(ByVal value As String)
            If Not Equals(_cCT_ID_AFP, value) Then
                ChangeTracker.RecordOriginalValue("CCT_ID_AFP", _cCT_ID_AFP)
                If Not IsDeserializing Then
                    If CtaCte IsNot Nothing AndAlso Not Equals(CtaCte.CCT_ID, value) Then
                        CtaCte = Nothing
                    End If
                End If
                _cCT_ID_AFP = value
                OnPropertyChanged("CCT_ID_AFP")
            End If
        End Set
    End Property

    Private _cCT_ID_AFP As String

    <DataMember()>
    Public Property DOC_SERIE_AFP() As String
        Get
            Return _dOC_SERIE_AFP
        End Get
        Set(ByVal value As String)
            If Not Equals(_dOC_SERIE_AFP, value) Then
                _dOC_SERIE_AFP = value
                OnPropertyChanged("DOC_SERIE_AFP")
            End If
        End Set
    End Property

    Private _dOC_SERIE_AFP As String

    <DataMember()>
    Public Property DOC_NUMERO_AFP() As String
        Get
            Return _dOC_NUMERO_AFP
        End Get
        Set(ByVal value As String)
            If Not Equals(_dOC_NUMERO_AFP, value) Then
                _dOC_NUMERO_AFP = value
                OnPropertyChanged("DOC_NUMERO_AFP")
            End If
        End Set
    End Property

    Private _dOC_NUMERO_AFP As String

    <DataMember()>
    Public Property ART_ID() As String
        Get
            Return _aRT_ID
        End Get
        Set(ByVal value As String)
            If Not Equals(_aRT_ID, value) Then
                ChangeTracker.RecordOriginalValue("ART_ID", _aRT_ID)
                If Not IsDeserializing Then
                    If Articulos IsNot Nothing AndAlso Not Equals(Articulos.ART_ID, value) Then
                        Articulos = Nothing
                    End If
                End If
                _aRT_ID = value
                OnPropertyChanged("ART_ID")
            End If
        End Set
    End Property

    Private _aRT_ID As String

    <DataMember()>
    Public Property DAP_CANTIDAD() As Decimal
        Get
            Return _dAP_CANTIDAD
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_dAP_CANTIDAD, value) Then
                _dAP_CANTIDAD = value
                OnPropertyChanged("DAP_CANTIDAD")
            End If
        End Set
    End Property

    Private _dAP_CANTIDAD As Decimal

    <DataMember()>
    Public Property DAP_OBS() As String
        Get
            Return _dAP_OBS
        End Get
        Set(ByVal value As String)
            If Not Equals(_dAP_OBS, value) Then
                _dAP_OBS = value
                OnPropertyChanged("DAP_OBS")
            End If
        End Set
    End Property

    Private _dAP_OBS As String

    <DataMember()>
    Public Property USU_ID() As String
        Get
            Return _uSU_ID
        End Get
        Set(ByVal value As String)
            If Not Equals(_uSU_ID, value) Then
                ChangeTracker.RecordOriginalValue("USU_ID", _uSU_ID)
                If Not IsDeserializing Then
                    If Usuarios IsNot Nothing AndAlso Not Equals(Usuarios.USU_ID, value) Then
                        Usuarios = Nothing
                    End If
                End If
                _uSU_ID = value
                OnPropertyChanged("USU_ID")
            End If
        End Set
    End Property

    Private _uSU_ID As String

    <DataMember()>
    Public Property DAP_FEC_GRAB() As Date
        Get
            Return _dAP_FEC_GRAB
        End Get
        Set(ByVal value As Date)
            If Not Equals(_dAP_FEC_GRAB, value) Then
                _dAP_FEC_GRAB = value
                OnPropertyChanged("DAP_FEC_GRAB")
            End If
        End Set
    End Property

    Private _dAP_FEC_GRAB As Date

    <DataMember()>
    Public Property DAP_ESTADO() As Boolean
        Get
            Return _dAP_ESTADO
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_dAP_ESTADO, value) Then
                _dAP_ESTADO = value
                OnPropertyChanged("DAP_ESTADO")
            End If
        End Set
    End Property

    Private _dAP_ESTADO As Boolean

    <DataMember()>
    Public Property TDO_ID_DEV() As String
        Get
            Return _tDO_ID_DEV
        End Get
        Set(ByVal value As String)
            If Not Equals(_tDO_ID_DEV, value) Then
                _tDO_ID_DEV = value
                OnPropertyChanged("TDO_ID_DEV")
            End If
        End Set
    End Property

    Private _tDO_ID_DEV As String

    <DataMember()>
    Public Property DTD_ID_DEV() As String
        Get
            Return _dTD_ID_DEV
        End Get
        Set(ByVal value As String)
            If Not Equals(_dTD_ID_DEV, value) Then
                _dTD_ID_DEV = value
                OnPropertyChanged("DTD_ID_DEV")
            End If
        End Set
    End Property

    Private _dTD_ID_DEV As String

    <DataMember()>
    Public Property CCT_ID_DEV() As String
        Get
            Return _cCT_ID_DEV
        End Get
        Set(ByVal value As String)
            If Not Equals(_cCT_ID_DEV, value) Then
                _cCT_ID_DEV = value
                OnPropertyChanged("CCT_ID_DEV")
            End If
        End Set
    End Property

    Private _cCT_ID_DEV As String

    <DataMember()>
    Public Property DES_SERIE_DEV() As String
        Get
            Return _dES_SERIE_DEV
        End Get
        Set(ByVal value As String)
            If Not Equals(_dES_SERIE_DEV, value) Then
                _dES_SERIE_DEV = value
                OnPropertyChanged("DES_SERIE_DEV")
            End If
        End Set
    End Property

    Private _dES_SERIE_DEV As String

    <DataMember()>
    Public Property DES_NUMERO_DEV() As String
        Get
            Return _dES_NUMERO_DEV
        End Get
        Set(ByVal value As String)
            If Not Equals(_dES_NUMERO_DEV, value) Then
                _dES_NUMERO_DEV = value
                OnPropertyChanged("DES_NUMERO_DEV")
            End If
        End Set
    End Property

    Private _dES_NUMERO_DEV As String

    <DataMember()>
    Public Property ART_ID_DEV() As String
        Get
            Return _aRT_ID_DEV
        End Get
        Set(ByVal value As String)
            If Not Equals(_aRT_ID_DEV, value) Then
                _aRT_ID_DEV = value
                OnPropertyChanged("ART_ID_DEV")
            End If
        End Set
    End Property

    Private _aRT_ID_DEV As String

    <DataMember()>
    Public Property DDE_CANTIDAD_DEV() As Nullable(Of Decimal)
        Get
            Return _dDE_CANTIDAD_DEV
        End Get
        Set(ByVal value As Nullable(Of Decimal))
            If Not Equals(_dDE_CANTIDAD_DEV, value) Then
                _dDE_CANTIDAD_DEV = value
                OnPropertyChanged("DDE_CANTIDAD_DEV")
            End If
        End Set
    End Property

    Private _dDE_CANTIDAD_DEV As Nullable(Of Decimal)

#End Region
#Region "Propiedades de navegación"

    <DataMember()>
    Public Property Articulos() As Articulos
        Get
            Return _articulos
        End Get
        Set(ByVal value As Articulos)
            If _articulos IsNot value Then
                Dim previousValue As Articulos = _articulos
                _articulos = value
                FixupArticulos(previousValue)
                OnNavigationPropertyChanged("Articulos")
            End If
        End Set
    End Property

    Private _articulos As Articulos


    <DataMember()>
    Public Property CtaCte() As CtaCte
        Get
            Return _ctaCte
        End Get
        Set(ByVal value As CtaCte)
            If _ctaCte IsNot value Then
                Dim previousValue As CtaCte = _ctaCte
                _ctaCte = value
                FixupCtaCte(previousValue)
                OnNavigationPropertyChanged("CtaCte")
            End If
        End Set
    End Property

    Private _ctaCte As CtaCte


    <DataMember()>
    Public Property DetalleTipoDocumentos() As DetalleTipoDocumentos
        Get
            Return _detalleTipoDocumentos
        End Get
        Set(ByVal value As DetalleTipoDocumentos)
            If _detalleTipoDocumentos IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added AndAlso value IsNot Nothing Then
                    ' Este es el extremo dependiente de una relación de identificación por lo que el extremo principal no se puede cambiar si ya está establecido;
                    ' de lo contrario, solo se puede establecer en una entidad con una clave primaria que tenga el mismo valor que la clave externa del extremo dependiente.
                    If Not Equals(DTD_ID, value.DTD_ID) Then
                        Throw New InvalidOperationException("El extremo principal de una relación de identificación solo se puede modificar cuando el extremo dependiente se encuentra en el estado agregado.")
                    End If
                End If
                Dim previousValue As DetalleTipoDocumentos = _detalleTipoDocumentos
                _detalleTipoDocumentos = value
                FixupDetalleTipoDocumentos(previousValue)
                OnNavigationPropertyChanged("DetalleTipoDocumentos")
            End If
        End Set
    End Property

    Private _detalleTipoDocumentos As DetalleTipoDocumentos


    <DataMember()>
    Public Property DetalleTipoDocumentos1() As DetalleTipoDocumentos
        Get
            Return _detalleTipoDocumentos1
        End Get
        Set(ByVal value As DetalleTipoDocumentos)
            If _detalleTipoDocumentos1 IsNot value Then
                Dim previousValue As DetalleTipoDocumentos = _detalleTipoDocumentos1
                _detalleTipoDocumentos1 = value
                FixupDetalleTipoDocumentos1(previousValue)
                OnNavigationPropertyChanged("DetalleTipoDocumentos1")
            End If
        End Set
    End Property

    Private _detalleTipoDocumentos1 As DetalleTipoDocumentos


    <DataMember()>
    Public Property TipoDocumentos() As TipoDocumentos
        Get
            Return _tipoDocumentos
        End Get
        Set(ByVal value As TipoDocumentos)
            If _tipoDocumentos IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added AndAlso value IsNot Nothing Then
                    ' Este es el extremo dependiente de una relación de identificación por lo que el extremo principal no se puede cambiar si ya está establecido;
                    ' de lo contrario, solo se puede establecer en una entidad con una clave primaria que tenga el mismo valor que la clave externa del extremo dependiente.
                    If Not Equals(TDO_ID, value.TDO_ID) Then
                        Throw New InvalidOperationException("El extremo principal de una relación de identificación solo se puede modificar cuando el extremo dependiente se encuentra en el estado agregado.")
                    End If
                End If
                Dim previousValue As TipoDocumentos = _tipoDocumentos
                _tipoDocumentos = value
                FixupTipoDocumentos(previousValue)
                OnNavigationPropertyChanged("TipoDocumentos")
            End If
        End Set
    End Property

    Private _tipoDocumentos As TipoDocumentos


    <DataMember()>
    Public Property TipoDocumentos1() As TipoDocumentos
        Get
            Return _tipoDocumentos1
        End Get
        Set(ByVal value As TipoDocumentos)
            If _tipoDocumentos1 IsNot value Then
                Dim previousValue As TipoDocumentos = _tipoDocumentos1
                _tipoDocumentos1 = value
                FixupTipoDocumentos1(previousValue)
                OnNavigationPropertyChanged("TipoDocumentos1")
            End If
        End Set
    End Property

    Private _tipoDocumentos1 As TipoDocumentos


    <DataMember()>
    Public Property Usuarios() As Usuarios
        Get
            Return _usuarios
        End Get
        Set(ByVal value As Usuarios)
            If _usuarios IsNot value Then
                Dim previousValue As Usuarios = _usuarios
                _usuarios = value
                FixupUsuarios(previousValue)
                OnNavigationPropertyChanged("Usuarios")
            End If
        End Set
    End Property

    Private _usuarios As Usuarios


#End Region
#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    ' Este tipo de entidad es el extremo dependiente en al menos una asociación que realiza eliminaciones en cascada.
    ' Este controlador de eventos procesará notificaciones que tienen lugar cuando se elimina el extremo principal.
    Friend Sub HandleCascadeDelete(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.MarkAsDeleted()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        Articulos = Nothing
        CtaCte = Nothing
        DetalleTipoDocumentos = Nothing
        DetalleTipoDocumentos1 = Nothing
        TipoDocumentos = Nothing
        TipoDocumentos1 = Nothing
        Usuarios = Nothing
    End Sub

#End Region
#Region "Corrección de asociación"

    Private Sub FixupArticulos(ByVal previousValue As Articulos)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.DetalleAfectaProductoDocumentos.Contains(Me) Then
            previousValue.DetalleAfectaProductoDocumentos.Remove(Me)
        End If

        If Articulos IsNot Nothing Then
            If Not Articulos.DetalleAfectaProductoDocumentos.Contains(Me) Then
                Articulos.DetalleAfectaProductoDocumentos.Add(Me)
            End If

            ART_ID = Articulos.ART_ID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Articulos") AndAlso
                ChangeTracker.OriginalValues("Articulos") Is Articulos Then
                ChangeTracker.OriginalValues.Remove("Articulos")
            Else
                ChangeTracker.RecordOriginalValue("Articulos", previousValue)
            End If
            If Articulos IsNot Nothing AndAlso Not Articulos.ChangeTracker.ChangeTrackingEnabled Then
                Articulos.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupCtaCte(ByVal previousValue As CtaCte)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.DetalleAfectaProductoDocumentos.Contains(Me) Then
            previousValue.DetalleAfectaProductoDocumentos.Remove(Me)
        End If

        If CtaCte IsNot Nothing Then
            If Not CtaCte.DetalleAfectaProductoDocumentos.Contains(Me) Then
                CtaCte.DetalleAfectaProductoDocumentos.Add(Me)
            End If

            CCT_ID_AFP = CtaCte.CCT_ID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("CtaCte") AndAlso
                ChangeTracker.OriginalValues("CtaCte") Is CtaCte Then
                ChangeTracker.OriginalValues.Remove("CtaCte")
            Else
                ChangeTracker.RecordOriginalValue("CtaCte", previousValue)
            End If
            If CtaCte IsNot Nothing AndAlso Not CtaCte.ChangeTracker.ChangeTrackingEnabled Then
                CtaCte.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupDetalleTipoDocumentos(ByVal previousValue As DetalleTipoDocumentos)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.DetalleAfectaProductoDocumentos.Contains(Me) Then
            previousValue.DetalleAfectaProductoDocumentos.Remove(Me)
        End If

        If DetalleTipoDocumentos IsNot Nothing Then
            If Not DetalleTipoDocumentos.DetalleAfectaProductoDocumentos.Contains(Me) Then
                DetalleTipoDocumentos.DetalleAfectaProductoDocumentos.Add(Me)
            End If

            DTD_ID = DetalleTipoDocumentos.DTD_ID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("DetalleTipoDocumentos") AndAlso
                ChangeTracker.OriginalValues("DetalleTipoDocumentos") Is DetalleTipoDocumentos Then
                ChangeTracker.OriginalValues.Remove("DetalleTipoDocumentos")
            Else
                ChangeTracker.RecordOriginalValue("DetalleTipoDocumentos", previousValue)
            End If
            If DetalleTipoDocumentos IsNot Nothing AndAlso Not DetalleTipoDocumentos.ChangeTracker.ChangeTrackingEnabled Then
                DetalleTipoDocumentos.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupDetalleTipoDocumentos1(ByVal previousValue As DetalleTipoDocumentos)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.DetalleAfectaProductoDocumentos1.Contains(Me) Then
            previousValue.DetalleAfectaProductoDocumentos1.Remove(Me)
        End If

        If DetalleTipoDocumentos1 IsNot Nothing Then
            If Not DetalleTipoDocumentos1.DetalleAfectaProductoDocumentos1.Contains(Me) Then
                DetalleTipoDocumentos1.DetalleAfectaProductoDocumentos1.Add(Me)
            End If

            DTD_ID_AFP = DetalleTipoDocumentos1.DTD_ID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("DetalleTipoDocumentos1") AndAlso
                ChangeTracker.OriginalValues("DetalleTipoDocumentos1") Is DetalleTipoDocumentos1 Then
                ChangeTracker.OriginalValues.Remove("DetalleTipoDocumentos1")
            Else
                ChangeTracker.RecordOriginalValue("DetalleTipoDocumentos1", previousValue)
            End If
            If DetalleTipoDocumentos1 IsNot Nothing AndAlso Not DetalleTipoDocumentos1.ChangeTracker.ChangeTrackingEnabled Then
                DetalleTipoDocumentos1.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupTipoDocumentos(ByVal previousValue As TipoDocumentos)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.DetalleAfectaProductoDocumentos.Contains(Me) Then
            previousValue.DetalleAfectaProductoDocumentos.Remove(Me)
        End If

        If TipoDocumentos IsNot Nothing Then
            If Not TipoDocumentos.DetalleAfectaProductoDocumentos.Contains(Me) Then
                TipoDocumentos.DetalleAfectaProductoDocumentos.Add(Me)
            End If

            TDO_ID = TipoDocumentos.TDO_ID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("TipoDocumentos") AndAlso
                ChangeTracker.OriginalValues("TipoDocumentos") Is TipoDocumentos Then
                ChangeTracker.OriginalValues.Remove("TipoDocumentos")
            Else
                ChangeTracker.RecordOriginalValue("TipoDocumentos", previousValue)
            End If
            If TipoDocumentos IsNot Nothing AndAlso Not TipoDocumentos.ChangeTracker.ChangeTrackingEnabled Then
                TipoDocumentos.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupTipoDocumentos1(ByVal previousValue As TipoDocumentos)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.DetalleAfectaProductoDocumentos1.Contains(Me) Then
            previousValue.DetalleAfectaProductoDocumentos1.Remove(Me)
        End If

        If TipoDocumentos1 IsNot Nothing Then
            If Not TipoDocumentos1.DetalleAfectaProductoDocumentos1.Contains(Me) Then
                TipoDocumentos1.DetalleAfectaProductoDocumentos1.Add(Me)
            End If

            TDO_ID_AFP = TipoDocumentos1.TDO_ID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("TipoDocumentos1") AndAlso
                ChangeTracker.OriginalValues("TipoDocumentos1") Is TipoDocumentos1 Then
                ChangeTracker.OriginalValues.Remove("TipoDocumentos1")
            Else
                ChangeTracker.RecordOriginalValue("TipoDocumentos1", previousValue)
            End If
            If TipoDocumentos1 IsNot Nothing AndAlso Not TipoDocumentos1.ChangeTracker.ChangeTrackingEnabled Then
                TipoDocumentos1.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupUsuarios(ByVal previousValue As Usuarios)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.DetalleAfectaProductoDocumentos.Contains(Me) Then
            previousValue.DetalleAfectaProductoDocumentos.Remove(Me)
        End If

        If Usuarios IsNot Nothing Then
            If Not Usuarios.DetalleAfectaProductoDocumentos.Contains(Me) Then
                Usuarios.DetalleAfectaProductoDocumentos.Add(Me)
            End If

            USU_ID = Usuarios.USU_ID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Usuarios") AndAlso
                ChangeTracker.OriginalValues("Usuarios") Is Usuarios Then
                ChangeTracker.OriginalValues.Remove("Usuarios")
            Else
                ChangeTracker.RecordOriginalValue("Usuarios", previousValue)
            End If
            If Usuarios IsNot Nothing AndAlso Not Usuarios.ChangeTracker.ChangeTrackingEnabled Then
                Usuarios.StartTracking()
            End If
        End If
    End Sub

#End Region
End Class
