'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
'     el código se vuelve a generar.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices

<DataContract(IsReference:=True)>
<KnownType(GetType(Usuarios))>
<KnownType(GetType(DetallePermisosTrabajador))>
<KnownType(GetType(Personas))>
Partial Public Class PermisosTrabajador
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Propiedades primitivas"


	<DataContract()> Partial Public Structure PropertyNames
				public shared prm_Numero As string = "prm_Numero"
				public shared prm_Fecha As string = "prm_Fecha"
				public shared prm_Motivo As string = "prm_Motivo"
				public shared per_IdTrabajador As string = "per_IdTrabajador"
				public shared per_IdAutoriza As string = "per_IdAutoriza"
				public shared prm_EsRenumerado As string = "prm_EsRenumerado"
				public shared prm_Observaciones As string = "prm_Observaciones"
				public shared Usu_Id As string = "Usu_Id"
				public shared prm_FecGrab As string = "prm_FecGrab"
		    End Structure
	



    <DataMember()>
    Public Property prm_Numero() As String
        Get
            Return _prm_Numero
        End Get
        Set(ByVal value As String)
            If Not Equals(_prm_Numero, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("La propiedad 'prm_Numero' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.")
                End If
                _prm_Numero = value
                OnPropertyChanged("prm_Numero")
            End If
        End Set
    End Property

    Private _prm_Numero As String

    <DataMember()>
    Public Property prm_Fecha() As Date
        Get
            Return _prm_Fecha
        End Get
        Set(ByVal value As Date)
            If Not Equals(_prm_Fecha, value) Then
                _prm_Fecha = value
                OnPropertyChanged("prm_Fecha")
            End If
        End Set
    End Property

    Private _prm_Fecha As Date

    <DataMember()>
    Public Property prm_Motivo() As String
        Get
            Return _prm_Motivo
        End Get
        Set(ByVal value As String)
            If Not Equals(_prm_Motivo, value) Then
                _prm_Motivo = value
                OnPropertyChanged("prm_Motivo")
            End If
        End Set
    End Property

    Private _prm_Motivo As String

    <DataMember()>
    Public Property per_IdTrabajador() As String
        Get
            Return _per_IdTrabajador
        End Get
        Set(ByVal value As String)
            If Not Equals(_per_IdTrabajador, value) Then
                ChangeTracker.RecordOriginalValue("per_IdTrabajador", _per_IdTrabajador)
                If Not IsDeserializing Then
                    If Personas IsNot Nothing AndAlso Not Equals(Personas.PER_ID, value) Then
                        Personas = Nothing
                    End If
                End If
                _per_IdTrabajador = value
                OnPropertyChanged("per_IdTrabajador")
            End If
        End Set
    End Property

    Private _per_IdTrabajador As String

    <DataMember()>
    Public Property per_IdAutoriza() As String
        Get
            Return _per_IdAutoriza
        End Get
        Set(ByVal value As String)
            If Not Equals(_per_IdAutoriza, value) Then
                ChangeTracker.RecordOriginalValue("per_IdAutoriza", _per_IdAutoriza)
                If Not IsDeserializing Then
                    If Personas1 IsNot Nothing AndAlso Not Equals(Personas1.PER_ID, value) Then
                        Personas1 = Nothing
                    End If
                End If
                _per_IdAutoriza = value
                OnPropertyChanged("per_IdAutoriza")
            End If
        End Set
    End Property

    Private _per_IdAutoriza As String

    <DataMember()>
    Public Property prm_EsRenumerado() As Boolean
        Get
            Return _prm_EsRenumerado
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_prm_EsRenumerado, value) Then
                _prm_EsRenumerado = value
                OnPropertyChanged("prm_EsRenumerado")
            End If
        End Set
    End Property

    Private _prm_EsRenumerado As Boolean

    <DataMember()>
    Public Property prm_Observaciones() As String
        Get
            Return _prm_Observaciones
        End Get
        Set(ByVal value As String)
            If Not Equals(_prm_Observaciones, value) Then
                _prm_Observaciones = value
                OnPropertyChanged("prm_Observaciones")
            End If
        End Set
    End Property

    Private _prm_Observaciones As String

    <DataMember()>
    Public Property Usu_Id() As String
        Get
            Return _usu_Id
        End Get
        Set(ByVal value As String)
            If Not Equals(_usu_Id, value) Then
                ChangeTracker.RecordOriginalValue("Usu_Id", _usu_Id)
                If Not IsDeserializing Then
                    If Usuarios IsNot Nothing AndAlso Not Equals(Usuarios.USU_ID, value) Then
                        Usuarios = Nothing
                    End If
                End If
                _usu_Id = value
                OnPropertyChanged("Usu_Id")
            End If
        End Set
    End Property

    Private _usu_Id As String

    <DataMember()>
    Public Property prm_FecGrab() As Date
        Get
            Return _prm_FecGrab
        End Get
        Set(ByVal value As Date)
            If Not Equals(_prm_FecGrab, value) Then
                _prm_FecGrab = value
                OnPropertyChanged("prm_FecGrab")
            End If
        End Set
    End Property

    Private _prm_FecGrab As Date

#End Region
#Region "Propiedades de navegación"

    <DataMember()>
    Public Property Usuarios() As Usuarios
        Get
            Return _usuarios
        End Get
        Set(ByVal value As Usuarios)
            If _usuarios IsNot value Then
                Dim previousValue As Usuarios = _usuarios
                _usuarios = value
                FixupUsuarios(previousValue)
                OnNavigationPropertyChanged("Usuarios")
            End If
        End Set
    End Property

    Private _usuarios As Usuarios


    <DataMember()>
    Public Property DetallePermisosTrabajador() As TrackableCollection(Of DetallePermisosTrabajador)
        Get
            If _detallePermisosTrabajador Is Nothing Then
                _detallePermisosTrabajador = New TrackableCollection(Of DetallePermisosTrabajador)
                AddHandler _detallePermisosTrabajador.CollectionChanged, AddressOf FixupDetallePermisosTrabajador
            End If
            Return _detallePermisosTrabajador
        End Get
        Set(ByVal value As TrackableCollection(Of DetallePermisosTrabajador))
            If Not Object.ReferenceEquals(_detallePermisosTrabajador, value) Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("No se puede establecer el elemento FixupChangeTrackingCollection cuando se ha habilitado ChangeTracking")
                End If
                If _detallePermisosTrabajador IsNot Nothing Then
                    RemoveHandler _detallePermisosTrabajador.CollectionChanged, AddressOf FixupDetallePermisosTrabajador
                    ' Este es el extremo principal en una asociación que realiza eliminaciones en cascada.
                    ' Quitar el controlador de eventos de la eliminación en cascada para aquellas entidades de la colección actual.
                    For Each item As DetallePermisosTrabajador In _detallePermisosTrabajador
                        RemoveHandler ChangeTracker.ObjectStateChanging, AddressOf item.HandleCascadeDelete
                    Next
                End If
                _detallePermisosTrabajador = value
                If _detallePermisosTrabajador IsNot Nothing Then
                    AddHandler _detallePermisosTrabajador.CollectionChanged, AddressOf FixupDetallePermisosTrabajador
                    ' Este es el extremo principal en una asociación que realiza eliminaciones en cascada.
                    ' Agrega el controlador de eventos de eliminación en cascada para aquellas entidades que ya se encuentran en la nueva colección.
                    For Each item As DetallePermisosTrabajador In _detallePermisosTrabajador
                        AddHandler ChangeTracker.ObjectStateChanging, AddressOf item.HandleCascadeDelete
                    Next
                End If
                OnNavigationPropertyChanged("DetallePermisosTrabajador")
            End If
        End Set
    End Property

    Private _detallePermisosTrabajador As TrackableCollection(Of DetallePermisosTrabajador)

    <DataMember()>
    Public Property Personas() As Personas
        Get
            Return _personas
        End Get
        Set(ByVal value As Personas)
            If _personas IsNot value Then
                Dim previousValue As Personas = _personas
                _personas = value
                FixupPersonas(previousValue)
                OnNavigationPropertyChanged("Personas")
            End If
        End Set
    End Property

    Private _personas As Personas


    <DataMember()>
    Public Property Personas1() As Personas
        Get
            Return _personas1
        End Get
        Set(ByVal value As Personas)
            If _personas1 IsNot value Then
                Dim previousValue As Personas = _personas1
                _personas1 = value
                FixupPersonas1(previousValue)
                OnNavigationPropertyChanged("Personas1")
            End If
        End Set
    End Property

    Private _personas1 As Personas


#End Region
#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        Usuarios = Nothing
        DetallePermisosTrabajador.Clear()
        Personas = Nothing
        Personas1 = Nothing
    End Sub

#End Region
#Region "Corrección de asociación"

    Private Sub FixupUsuarios(ByVal previousValue As Usuarios)
        If IsDeserializing Then
            Return
        End If

        If Usuarios IsNot Nothing Then
            Usu_Id = Usuarios.USU_ID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Usuarios") AndAlso
                ChangeTracker.OriginalValues("Usuarios") Is Usuarios Then
                ChangeTracker.OriginalValues.Remove("Usuarios")
            Else
                ChangeTracker.RecordOriginalValue("Usuarios", previousValue)
            End If
            If Usuarios IsNot Nothing AndAlso Not Usuarios.ChangeTracker.ChangeTrackingEnabled Then
                Usuarios.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupPersonas(ByVal previousValue As Personas)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.PermisosTrabajador.Contains(Me) Then
            previousValue.PermisosTrabajador.Remove(Me)
        End If

        If Personas IsNot Nothing Then
            If Not Personas.PermisosTrabajador.Contains(Me) Then
                Personas.PermisosTrabajador.Add(Me)
            End If

            per_IdTrabajador = Personas.PER_ID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Personas") AndAlso
                ChangeTracker.OriginalValues("Personas") Is Personas Then
                ChangeTracker.OriginalValues.Remove("Personas")
            Else
                ChangeTracker.RecordOriginalValue("Personas", previousValue)
            End If
            If Personas IsNot Nothing AndAlso Not Personas.ChangeTracker.ChangeTrackingEnabled Then
                Personas.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupPersonas1(ByVal previousValue As Personas)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.PermisosTrabajador1.Contains(Me) Then
            previousValue.PermisosTrabajador1.Remove(Me)
        End If

        If Personas1 IsNot Nothing Then
            If Not Personas1.PermisosTrabajador1.Contains(Me) Then
                Personas1.PermisosTrabajador1.Add(Me)
            End If

            per_IdAutoriza = Personas1.PER_ID
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Personas1") AndAlso
                ChangeTracker.OriginalValues("Personas1") Is Personas1 Then
                ChangeTracker.OriginalValues.Remove("Personas1")
            Else
                ChangeTracker.RecordOriginalValue("Personas1", previousValue)
            End If
            If Personas1 IsNot Nothing AndAlso Not Personas1.ChangeTracker.ChangeTrackingEnabled Then
                Personas1.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupDetallePermisosTrabajador(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As DetallePermisosTrabajador In e.NewItems
                item.prm_Numero = prm_Numero
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("DetallePermisosTrabajador", item)
                End If
                ' Este es el extremo principal en una asociación que realiza eliminaciones en cascada.
                ' Actualizar la escucha de eventos para que se refiera al nuevo extremo dependiente.
                AddHandler ChangeTracker.ObjectStateChanging, AddressOf item.HandleCascadeDelete
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As DetallePermisosTrabajador In e.OldItems
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("DetallePermisosTrabajador", item)
                    ' Eliminar el extremo dependiente de esta asociación de identificación. Si el estado actual es agregado,
                    ' permite que la relación se modifique sin eliminar el elemento dependiente.
                    If item.ChangeTracker.State <> ObjectState.Added Then
                        item.MarkAsDeleted()
                    End If
                End If
                ' Este es el extremo principal en una asociación que realiza eliminaciones en cascada.
                ' Quitar el extremo dependiente anterior de la escucha de eventos.
                RemoveHandler ChangeTracker.ObjectStateChanging, AddressOf item.HandleCascadeDelete
            Next
        End If
    End Sub

#End Region
End Class
