'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
'     el código se vuelve a generar.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices

<DataContract(IsReference:=True)>
<KnownType(GetType(Personas))>
<KnownType(GetType(OrdenTrabajo))>
<KnownType(GetType(RendicionGastosDetalle))>
<KnownType(GetType(ProvisionCompras))>
<KnownType(GetType(CuentaRendirDetalle))>
Partial Public Class RendicionGastos
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Propiedades primitivas"


	<DataContract()> Partial Public Structure PropertyNames
				public shared RGA_ID As string = "RGA_ID"
				public shared RGA_FECHA As string = "RGA_FECHA"
				public shared PER_ID As string = "PER_ID"
				public shared USU_ID As string = "USU_ID"
				public shared RGA_FEC_GRAB As string = "RGA_FEC_GRAB"
				public shared RGA_ESTADO As string = "RGA_ESTADO"
				public shared OTR_ID As string = "OTR_ID"
		    End Structure
	



    <DataMember()>
    Public Property RGA_ID() As Integer
        Get
            Return _rGA_ID
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_rGA_ID, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("La propiedad 'RGA_ID' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.")
                End If
                _rGA_ID = value
                OnPropertyChanged("RGA_ID")
            End If
        End Set
    End Property

    Private _rGA_ID As Integer

    <DataMember()>
    Public Property RGA_FECHA() As Nullable(Of Date)
        Get
            Return _rGA_FECHA
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_rGA_FECHA, value) Then
                _rGA_FECHA = value
                OnPropertyChanged("RGA_FECHA")
            End If
        End Set
    End Property

    Private _rGA_FECHA As Nullable(Of Date)

    <DataMember()>
    Public Property PER_ID() As String
        Get
            Return _pER_ID
        End Get
        Set(ByVal value As String)
            If Not Equals(_pER_ID, value) Then
                ChangeTracker.RecordOriginalValue("PER_ID", _pER_ID)
                If Not IsDeserializing Then
                    If Personas IsNot Nothing AndAlso Not Equals(Personas.PER_ID, value) Then
                        Personas = Nothing
                    End If
                End If
                _pER_ID = value
                OnPropertyChanged("PER_ID")
            End If
        End Set
    End Property

    Private _pER_ID As String

    <DataMember()>
    Public Property USU_ID() As String
        Get
            Return _uSU_ID
        End Get
        Set(ByVal value As String)
            If Not Equals(_uSU_ID, value) Then
                _uSU_ID = value
                OnPropertyChanged("USU_ID")
            End If
        End Set
    End Property

    Private _uSU_ID As String

    <DataMember()>
    Public Property RGA_FEC_GRAB() As Nullable(Of Date)
        Get
            Return _rGA_FEC_GRAB
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_rGA_FEC_GRAB, value) Then
                _rGA_FEC_GRAB = value
                OnPropertyChanged("RGA_FEC_GRAB")
            End If
        End Set
    End Property

    Private _rGA_FEC_GRAB As Nullable(Of Date)

    <DataMember()>
    Public Property RGA_ESTADO() As Nullable(Of Boolean)
        Get
            Return _rGA_ESTADO
        End Get
        Set(ByVal value As Nullable(Of Boolean))
            If Not Equals(_rGA_ESTADO, value) Then
                _rGA_ESTADO = value
                OnPropertyChanged("RGA_ESTADO")
            End If
        End Set
    End Property

    Private _rGA_ESTADO As Nullable(Of Boolean)

    <DataMember()>
    Public Property OTR_ID() As Nullable(Of Integer)
        Get
            Return _oTR_ID
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_oTR_ID, value) Then
                ChangeTracker.RecordOriginalValue("OTR_ID", _oTR_ID)
                If Not IsDeserializing Then
                    If OrdenTrabajo IsNot Nothing AndAlso Not Equals(OrdenTrabajo.OTR_ID, value) Then
                        OrdenTrabajo = Nothing
                    End If
                End If
                _oTR_ID = value
                OnPropertyChanged("OTR_ID")
            End If
        End Set
    End Property

    Private _oTR_ID As Nullable(Of Integer)

#End Region
#Region "Propiedades de navegación"

    <DataMember()>
    Public Property Personas() As Personas
        Get
            Return _personas
        End Get
        Set(ByVal value As Personas)
            If _personas IsNot value Then
                Dim previousValue As Personas = _personas
                _personas = value
                FixupPersonas(previousValue)
                OnNavigationPropertyChanged("Personas")
            End If
        End Set
    End Property

    Private _personas As Personas


    <DataMember()>
    Public Property OrdenTrabajo() As OrdenTrabajo
        Get
            Return _ordenTrabajo
        End Get
        Set(ByVal value As OrdenTrabajo)
            If _ordenTrabajo IsNot value Then
                Dim previousValue As OrdenTrabajo = _ordenTrabajo
                _ordenTrabajo = value
                FixupOrdenTrabajo(previousValue)
                OnNavigationPropertyChanged("OrdenTrabajo")
            End If
        End Set
    End Property

    Private _ordenTrabajo As OrdenTrabajo


    <DataMember()>
    Public Property RendicionGastosDetalle() As TrackableCollection(Of RendicionGastosDetalle)
        Get
            If _rendicionGastosDetalle Is Nothing Then
                _rendicionGastosDetalle = New TrackableCollection(Of RendicionGastosDetalle)
                AddHandler _rendicionGastosDetalle.CollectionChanged, AddressOf FixupRendicionGastosDetalle
            End If
            Return _rendicionGastosDetalle
        End Get
        Set(ByVal value As TrackableCollection(Of RendicionGastosDetalle))
            If Not Object.ReferenceEquals(_rendicionGastosDetalle, value) Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("No se puede establecer el elemento FixupChangeTrackingCollection cuando se ha habilitado ChangeTracking")
                End If
                If _rendicionGastosDetalle IsNot Nothing Then
                    RemoveHandler _rendicionGastosDetalle.CollectionChanged, AddressOf FixupRendicionGastosDetalle
                End If
                _rendicionGastosDetalle = value
                If _rendicionGastosDetalle IsNot Nothing Then
                    AddHandler _rendicionGastosDetalle.CollectionChanged, AddressOf FixupRendicionGastosDetalle
                End If
                OnNavigationPropertyChanged("RendicionGastosDetalle")
            End If
        End Set
    End Property

    Private _rendicionGastosDetalle As TrackableCollection(Of RendicionGastosDetalle)

    <DataMember()>
    Public Property ProvisionCompras() As TrackableCollection(Of ProvisionCompras)
        Get
            If _provisionCompras Is Nothing Then
                _provisionCompras = New TrackableCollection(Of ProvisionCompras)
                AddHandler _provisionCompras.CollectionChanged, AddressOf FixupProvisionCompras
            End If
            Return _provisionCompras
        End Get
        Set(ByVal value As TrackableCollection(Of ProvisionCompras))
            If Not Object.ReferenceEquals(_provisionCompras, value) Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("No se puede establecer el elemento FixupChangeTrackingCollection cuando se ha habilitado ChangeTracking")
                End If
                If _provisionCompras IsNot Nothing Then
                    RemoveHandler _provisionCompras.CollectionChanged, AddressOf FixupProvisionCompras
                End If
                _provisionCompras = value
                If _provisionCompras IsNot Nothing Then
                    AddHandler _provisionCompras.CollectionChanged, AddressOf FixupProvisionCompras
                End If
                OnNavigationPropertyChanged("ProvisionCompras")
            End If
        End Set
    End Property

    Private _provisionCompras As TrackableCollection(Of ProvisionCompras)

    <DataMember()>
    Public Property CuentaRendirDetalle() As TrackableCollection(Of CuentaRendirDetalle)
        Get
            If _cuentaRendirDetalle Is Nothing Then
                _cuentaRendirDetalle = New TrackableCollection(Of CuentaRendirDetalle)
                AddHandler _cuentaRendirDetalle.CollectionChanged, AddressOf FixupCuentaRendirDetalle
            End If
            Return _cuentaRendirDetalle
        End Get
        Set(ByVal value As TrackableCollection(Of CuentaRendirDetalle))
            If Not Object.ReferenceEquals(_cuentaRendirDetalle, value) Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("No se puede establecer el elemento FixupChangeTrackingCollection cuando se ha habilitado ChangeTracking")
                End If
                If _cuentaRendirDetalle IsNot Nothing Then
                    RemoveHandler _cuentaRendirDetalle.CollectionChanged, AddressOf FixupCuentaRendirDetalle
                End If
                _cuentaRendirDetalle = value
                If _cuentaRendirDetalle IsNot Nothing Then
                    AddHandler _cuentaRendirDetalle.CollectionChanged, AddressOf FixupCuentaRendirDetalle
                End If
                OnNavigationPropertyChanged("CuentaRendirDetalle")
            End If
        End Set
    End Property

    Private _cuentaRendirDetalle As TrackableCollection(Of CuentaRendirDetalle)

#End Region
#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        Personas = Nothing
        OrdenTrabajo = Nothing
        RendicionGastosDetalle.Clear()
        ProvisionCompras.Clear()
        CuentaRendirDetalle.Clear()
    End Sub

#End Region
#Region "Corrección de asociación"

    Private Sub FixupPersonas(ByVal previousValue As Personas, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.RendicionGastos.Contains(Me) Then
            previousValue.RendicionGastos.Remove(Me)
        End If

        If Personas IsNot Nothing Then
            If Not Personas.RendicionGastos.Contains(Me) Then
                Personas.RendicionGastos.Add(Me)
            End If

            PER_ID = Personas.PER_ID
        ElseIf Not skipKeys Then
            PER_ID = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Personas") AndAlso
                ChangeTracker.OriginalValues("Personas") Is Personas Then
                ChangeTracker.OriginalValues.Remove("Personas")
            Else
                ChangeTracker.RecordOriginalValue("Personas", previousValue)
            End If
            If Personas IsNot Nothing AndAlso Not Personas.ChangeTracker.ChangeTrackingEnabled Then
                Personas.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupOrdenTrabajo(ByVal previousValue As OrdenTrabajo, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.RendicionGastos.Contains(Me) Then
            previousValue.RendicionGastos.Remove(Me)
        End If

        If OrdenTrabajo IsNot Nothing Then
            If Not OrdenTrabajo.RendicionGastos.Contains(Me) Then
                OrdenTrabajo.RendicionGastos.Add(Me)
            End If

            OTR_ID = OrdenTrabajo.OTR_ID
        ElseIf Not skipKeys Then
            OTR_ID = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("OrdenTrabajo") AndAlso
                ChangeTracker.OriginalValues("OrdenTrabajo") Is OrdenTrabajo Then
                ChangeTracker.OriginalValues.Remove("OrdenTrabajo")
            Else
                ChangeTracker.RecordOriginalValue("OrdenTrabajo", previousValue)
            End If
            If OrdenTrabajo IsNot Nothing AndAlso Not OrdenTrabajo.ChangeTracker.ChangeTrackingEnabled Then
                OrdenTrabajo.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupRendicionGastosDetalle(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As RendicionGastosDetalle In e.NewItems
                item.RendicionGastos = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("RendicionGastosDetalle", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As RendicionGastosDetalle In e.OldItems
                If ReferenceEquals(item.RendicionGastos, Me) Then
                    item.RendicionGastos = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("RendicionGastosDetalle", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupProvisionCompras(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As ProvisionCompras In e.NewItems
                item.RendicionGastos = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("ProvisionCompras", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As ProvisionCompras In e.OldItems
                If ReferenceEquals(item.RendicionGastos, Me) Then
                    item.RendicionGastos = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("ProvisionCompras", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupCuentaRendirDetalle(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As CuentaRendirDetalle In e.NewItems
                item.RendicionGastos = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("CuentaRendirDetalle", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As CuentaRendirDetalle In e.OldItems
                If ReferenceEquals(item.RendicionGastos, Me) Then
                    item.RendicionGastos = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("CuentaRendirDetalle", item)
                End If
            Next
        End If
    End Sub

#End Region
End Class
