'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
'     el código se vuelve a generar.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices

<DataContract(IsReference:=True)>
<KnownType(GetType(Personas))>
<KnownType(GetType(SolicitudSoporteDetalle))>
Partial Public Class SolicitudSoporte
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Propiedades primitivas"


	<DataContract()> Partial Public Structure PropertyNames
				public shared SOS_ID As string = "SOS_ID"
				public shared PER_ID_SOLICITADO As string = "PER_ID_SOLICITADO"
				public shared SOS_FECHA As string = "SOS_FECHA"
				public shared SOS_AREA As string = "SOS_AREA"
				public shared SOS_DESCRIPCION As string = "SOS_DESCRIPCION"
				public shared PER_ID_AUTORIZADO As string = "PER_ID_AUTORIZADO"
				public shared SOS_CONFORMIDAD As string = "SOS_CONFORMIDAD"
				public shared SOS_DESCRIPCION_CONFORMIDAD As string = "SOS_DESCRIPCION_CONFORMIDAD"
				public shared USU_ID As string = "USU_ID"
				public shared SOS_FEC_GRAB As string = "SOS_FEC_GRAB"
				public shared SOS_ESTADO As string = "SOS_ESTADO"
				public shared SOS_TIPO As string = "SOS_TIPO"
				public shared SOS_SUB_TIPO As string = "SOS_SUB_TIPO"
				public shared SOS_SISTEMA As string = "SOS_SISTEMA"
		    End Structure
	



    <DataMember()>
    Public Property SOS_ID() As Integer
        Get
            Return _sOS_ID
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_sOS_ID, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("La propiedad 'SOS_ID' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.")
                End If
                _sOS_ID = value
                OnPropertyChanged("SOS_ID")
            End If
        End Set
    End Property

    Private _sOS_ID As Integer

    <DataMember()>
    Public Property PER_ID_SOLICITADO() As String
        Get
            Return _pER_ID_SOLICITADO
        End Get
        Set(ByVal value As String)
            If Not Equals(_pER_ID_SOLICITADO, value) Then
                ChangeTracker.RecordOriginalValue("PER_ID_SOLICITADO", _pER_ID_SOLICITADO)
                If Not IsDeserializing Then
                    If Personas IsNot Nothing AndAlso Not Equals(Personas.PER_ID, value) Then
                        Personas = Nothing
                    End If
                End If
                _pER_ID_SOLICITADO = value
                OnPropertyChanged("PER_ID_SOLICITADO")
            End If
        End Set
    End Property

    Private _pER_ID_SOLICITADO As String

    <DataMember()>
    Public Property SOS_FECHA() As Nullable(Of Date)
        Get
            Return _sOS_FECHA
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_sOS_FECHA, value) Then
                _sOS_FECHA = value
                OnPropertyChanged("SOS_FECHA")
            End If
        End Set
    End Property

    Private _sOS_FECHA As Nullable(Of Date)

    <DataMember()>
    Public Property SOS_AREA() As String
        Get
            Return _sOS_AREA
        End Get
        Set(ByVal value As String)
            If Not Equals(_sOS_AREA, value) Then
                _sOS_AREA = value
                OnPropertyChanged("SOS_AREA")
            End If
        End Set
    End Property

    Private _sOS_AREA As String

    <DataMember()>
    Public Property SOS_DESCRIPCION() As String
        Get
            Return _sOS_DESCRIPCION
        End Get
        Set(ByVal value As String)
            If Not Equals(_sOS_DESCRIPCION, value) Then
                _sOS_DESCRIPCION = value
                OnPropertyChanged("SOS_DESCRIPCION")
            End If
        End Set
    End Property

    Private _sOS_DESCRIPCION As String

    <DataMember()>
    Public Property PER_ID_AUTORIZADO() As String
        Get
            Return _pER_ID_AUTORIZADO
        End Get
        Set(ByVal value As String)
            If Not Equals(_pER_ID_AUTORIZADO, value) Then
                ChangeTracker.RecordOriginalValue("PER_ID_AUTORIZADO", _pER_ID_AUTORIZADO)
                If Not IsDeserializing Then
                    If Personas1 IsNot Nothing AndAlso Not Equals(Personas1.PER_ID, value) Then
                        Personas1 = Nothing
                    End If
                End If
                _pER_ID_AUTORIZADO = value
                OnPropertyChanged("PER_ID_AUTORIZADO")
            End If
        End Set
    End Property

    Private _pER_ID_AUTORIZADO As String

    <DataMember()>
    Public Property SOS_CONFORMIDAD() As Nullable(Of Integer)
        Get
            Return _sOS_CONFORMIDAD
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_sOS_CONFORMIDAD, value) Then
                _sOS_CONFORMIDAD = value
                OnPropertyChanged("SOS_CONFORMIDAD")
            End If
        End Set
    End Property

    Private _sOS_CONFORMIDAD As Nullable(Of Integer)

    <DataMember()>
    Public Property SOS_DESCRIPCION_CONFORMIDAD() As String
        Get
            Return _sOS_DESCRIPCION_CONFORMIDAD
        End Get
        Set(ByVal value As String)
            If Not Equals(_sOS_DESCRIPCION_CONFORMIDAD, value) Then
                _sOS_DESCRIPCION_CONFORMIDAD = value
                OnPropertyChanged("SOS_DESCRIPCION_CONFORMIDAD")
            End If
        End Set
    End Property

    Private _sOS_DESCRIPCION_CONFORMIDAD As String

    <DataMember()>
    Public Property USU_ID() As String
        Get
            Return _uSU_ID
        End Get
        Set(ByVal value As String)
            If Not Equals(_uSU_ID, value) Then
                _uSU_ID = value
                OnPropertyChanged("USU_ID")
            End If
        End Set
    End Property

    Private _uSU_ID As String

    <DataMember()>
    Public Property SOS_FEC_GRAB() As Nullable(Of Date)
        Get
            Return _sOS_FEC_GRAB
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_sOS_FEC_GRAB, value) Then
                _sOS_FEC_GRAB = value
                OnPropertyChanged("SOS_FEC_GRAB")
            End If
        End Set
    End Property

    Private _sOS_FEC_GRAB As Nullable(Of Date)

    <DataMember()>
    Public Property SOS_ESTADO() As Nullable(Of Boolean)
        Get
            Return _sOS_ESTADO
        End Get
        Set(ByVal value As Nullable(Of Boolean))
            If Not Equals(_sOS_ESTADO, value) Then
                _sOS_ESTADO = value
                OnPropertyChanged("SOS_ESTADO")
            End If
        End Set
    End Property

    Private _sOS_ESTADO As Nullable(Of Boolean)

    <DataMember()>
    Public Property SOS_TIPO() As Nullable(Of Integer)
        Get
            Return _sOS_TIPO
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_sOS_TIPO, value) Then
                _sOS_TIPO = value
                OnPropertyChanged("SOS_TIPO")
            End If
        End Set
    End Property

    Private _sOS_TIPO As Nullable(Of Integer)

    <DataMember()>
    Public Property SOS_SUB_TIPO() As Nullable(Of Integer)
        Get
            Return _sOS_SUB_TIPO
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_sOS_SUB_TIPO, value) Then
                _sOS_SUB_TIPO = value
                OnPropertyChanged("SOS_SUB_TIPO")
            End If
        End Set
    End Property

    Private _sOS_SUB_TIPO As Nullable(Of Integer)

    <DataMember()>
    Public Property SOS_SISTEMA() As Nullable(Of Integer)
        Get
            Return _sOS_SISTEMA
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_sOS_SISTEMA, value) Then
                _sOS_SISTEMA = value
                OnPropertyChanged("SOS_SISTEMA")
            End If
        End Set
    End Property

    Private _sOS_SISTEMA As Nullable(Of Integer)

#End Region
#Region "Propiedades de navegación"

    <DataMember()>
    Public Property Personas() As Personas
        Get
            Return _personas
        End Get
        Set(ByVal value As Personas)
            If _personas IsNot value Then
                Dim previousValue As Personas = _personas
                _personas = value
                FixupPersonas(previousValue)
                OnNavigationPropertyChanged("Personas")
            End If
        End Set
    End Property

    Private _personas As Personas


    <DataMember()>
    Public Property Personas1() As Personas
        Get
            Return _personas1
        End Get
        Set(ByVal value As Personas)
            If _personas1 IsNot value Then
                Dim previousValue As Personas = _personas1
                _personas1 = value
                FixupPersonas1(previousValue)
                OnNavigationPropertyChanged("Personas1")
            End If
        End Set
    End Property

    Private _personas1 As Personas


    <DataMember()>
    Public Property SolicitudSoporteDetalle() As TrackableCollection(Of SolicitudSoporteDetalle)
        Get
            If _solicitudSoporteDetalle Is Nothing Then
                _solicitudSoporteDetalle = New TrackableCollection(Of SolicitudSoporteDetalle)
                AddHandler _solicitudSoporteDetalle.CollectionChanged, AddressOf FixupSolicitudSoporteDetalle
            End If
            Return _solicitudSoporteDetalle
        End Get
        Set(ByVal value As TrackableCollection(Of SolicitudSoporteDetalle))
            If Not Object.ReferenceEquals(_solicitudSoporteDetalle, value) Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("No se puede establecer el elemento FixupChangeTrackingCollection cuando se ha habilitado ChangeTracking")
                End If
                If _solicitudSoporteDetalle IsNot Nothing Then
                    RemoveHandler _solicitudSoporteDetalle.CollectionChanged, AddressOf FixupSolicitudSoporteDetalle
                End If
                _solicitudSoporteDetalle = value
                If _solicitudSoporteDetalle IsNot Nothing Then
                    AddHandler _solicitudSoporteDetalle.CollectionChanged, AddressOf FixupSolicitudSoporteDetalle
                End If
                OnNavigationPropertyChanged("SolicitudSoporteDetalle")
            End If
        End Set
    End Property

    Private _solicitudSoporteDetalle As TrackableCollection(Of SolicitudSoporteDetalle)

#End Region
#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        Personas = Nothing
        Personas1 = Nothing
        SolicitudSoporteDetalle.Clear()
    End Sub

#End Region
#Region "Corrección de asociación"

    Private Sub FixupPersonas(ByVal previousValue As Personas, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.SolicitudSoporte.Contains(Me) Then
            previousValue.SolicitudSoporte.Remove(Me)
        End If

        If Personas IsNot Nothing Then
            If Not Personas.SolicitudSoporte.Contains(Me) Then
                Personas.SolicitudSoporte.Add(Me)
            End If

            PER_ID_SOLICITADO = Personas.PER_ID
        ElseIf Not skipKeys Then
            PER_ID_SOLICITADO = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Personas") AndAlso
                ChangeTracker.OriginalValues("Personas") Is Personas Then
                ChangeTracker.OriginalValues.Remove("Personas")
            Else
                ChangeTracker.RecordOriginalValue("Personas", previousValue)
            End If
            If Personas IsNot Nothing AndAlso Not Personas.ChangeTracker.ChangeTrackingEnabled Then
                Personas.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupPersonas1(ByVal previousValue As Personas, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.SolicitudSoporte1.Contains(Me) Then
            previousValue.SolicitudSoporte1.Remove(Me)
        End If

        If Personas1 IsNot Nothing Then
            If Not Personas1.SolicitudSoporte1.Contains(Me) Then
                Personas1.SolicitudSoporte1.Add(Me)
            End If

            PER_ID_AUTORIZADO = Personas1.PER_ID
        ElseIf Not skipKeys Then
            PER_ID_AUTORIZADO = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Personas1") AndAlso
                ChangeTracker.OriginalValues("Personas1") Is Personas1 Then
                ChangeTracker.OriginalValues.Remove("Personas1")
            Else
                ChangeTracker.RecordOriginalValue("Personas1", previousValue)
            End If
            If Personas1 IsNot Nothing AndAlso Not Personas1.ChangeTracker.ChangeTrackingEnabled Then
                Personas1.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupSolicitudSoporteDetalle(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As SolicitudSoporteDetalle In e.NewItems
                item.SolicitudSoporte = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("SolicitudSoporteDetalle", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As SolicitudSoporteDetalle In e.OldItems
                If ReferenceEquals(item.SolicitudSoporte, Me) Then
                    item.SolicitudSoporte = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("SolicitudSoporteDetalle", item)
                End If
            Next
        End If
    End Sub

#End Region
End Class
